# fly.toml app configuration file generated for carsurebotdotnet on 2025-05-05T22:35:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'carsurebotdotnet'
primary_region = 'fra'

[build]

[[services]]
  
  name = "worker"
  
  type = "worker"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

  [scale]
  count = 1
